import type { NextPage } from "next";
import Head from "next/head";
import SpaceAddComponent from "../src/components/SpaceAddComponent";
import { AppContextProvider } from "../src/Context/AppContext";
import ChooseCompModal from "../src/components/Modal/ChooseCompModal";
import { useState } from "react";
import Navbar from "../src/components/Navbar/Navbar";
import BaseContextModal from "../src/components/Modal/BaseContextModal";
import SectionList from "../src/components/Section/SectionList";

const Home: NextPage = () => {
  const [compOpenModal, setOpenCompModal] = useState<boolean>(false);
  const [baseFormModal, setBaseFormModal] = useState<boolean>(false);

  const newLocal =
    "https://fonts.googleapis.com/css2?family=Righteous&family=Roboto&display=swap";

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href={newLocal} rel="stylesheet" />
      </Head>

      <AppContextProvider>
        <Navbar onClickSetting={() => setBaseFormModal(true)} />

        <SectionList />

        <SpaceAddComponent onClick={() => setOpenCompModal(true)} />
        
        {compOpenModal && (
          <ChooseCompModal onCloseModal={() => setOpenCompModal(false)} />
        )}

        {baseFormModal && (
          <BaseContextModal onCloseModal={() => setBaseFormModal(false)} />
        )}
      </AppContextProvider>
    </div>
  );
};

export default Home;
