import type { NextPage } from "next";
import Head from "next/head";
import SpaceAddComponent from "../src/components/SpaceAddComponent";
import Switcher from "../src/components/Switcher/Switcher";
import { AppContextProvider } from "../src/Context/AppContext";
import ChooseCompModal from "../src/components/Modal/ChooseCompModal";
import { useState } from "react";

const Home: NextPage = () => {
  const [openModal, setOpenModal] = useState<boolean>(false);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppContextProvider>
        <Switcher />
        <SpaceAddComponent onClick={() => setOpenModal(true)} />
        {openModal && (
          <ChooseCompModal onCloseModal={() => setOpenModal(false)} />
        )}
      </AppContextProvider>
    </div>
  );
};

export default Home;
